<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="4" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="314" started-at="2018-06-28T05:24:48Z" finished-at="2018-06-28T05:24:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="314" started-at="2018-06-28T05:24:48Z" finished-at="2018-06-28T05:24:48Z">
      <class name="testClasses.SNLTestCases">
        <test-method status="PASS" signature="initVars()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="initVars" is-config="true" duration-ms="48" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initVars -->
        <test-method status="PASS" signature="verifyAddingMoreThanFourUsers()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="verifyAddingMoreThanFourUsers" duration-ms="41" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:68)
	at actionClasses.BoardTest.addUser(BoardTest.java:51)
	at actionClasses.BoardTest.addMoreThanFourUsers(BoardTest.java:37)
	at testClasses.SNLTestCases.verifyAddingMoreThanFourUsers(SNLTestCases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddingMoreThanFourUsers -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="tearDown" is-config="true" duration-ms="39" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initVars()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="initVars" is-config="true" duration-ms="8" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initVars -->
        <test-method status="PASS" signature="verifyAddingSameNameUsers()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="verifyAddingSameNameUsers" duration-ms="5" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'some_name' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'some_name' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:73)
	at actionClasses.BoardTest.addUser(BoardTest.java:60)
	at actionClasses.BoardTest.addSameNameUsers(BoardTest.java:43)
	at testClasses.SNLTestCases.verifyAddingSameNameUsers(SNLTestCases.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddingSameNameUsers -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="tearDown" is-config="true" duration-ms="40" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initVars()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="initVars" is-config="true" duration-ms="4" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initVars -->
        <test-method status="PASS" signature="verifyDeleteUserWithoutRegisteringAnyUser()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="verifyDeleteUserWithoutRegisteringAnyUser" duration-ms="5" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.qainfotech.tap.training.snl.api.Board.deletePlayer(Board.java:111)
	at actionClasses.BoardTest.deleteUserWithoutRegisteringAnyUser(BoardTest.java:31)
	at testClasses.SNLTestCases.verifyDeleteUserWithoutRegisteringAnyUser(SNLTestCases.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDeleteUserWithoutRegisteringAnyUser -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="tearDown" is-config="true" duration-ms="25" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initVars()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="initVars" is-config="true" duration-ms="6" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initVars -->
        <test-method status="PASS" signature="verifyRollDiceWithoutRegisteringAnyUser()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="verifyRollDiceWithoutRegisteringAnyUser" duration-ms="2" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONArray[0] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONArray[0] not found.
	at org.json.JSONArray.get(JSONArray.java:201)
	at org.json.JSONArray.getJSONObject(JSONArray.java:364)
	at com.qainfotech.tap.training.snl.api.Board.rollDice(Board.java:131)
	at actionClasses.BoardTest.rollDiceWithoutRegisteringAnyUser(BoardTest.java:26)
	at testClasses.SNLTestCases.verifyRollDiceWithoutRegisteringAnyUser(SNLTestCases.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRollDiceWithoutRegisteringAnyUser -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testClasses.SNLTestCases@5ae9a829]" name="tearDown" is-config="true" duration-ms="33" started-at="2018-06-28T10:54:48Z" finished-at="2018-06-28T10:54:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.SNLTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
